### ISSUE TITLE
support comment-like syntaxes (tolerant parser)

### ISSUE THREAD

**Issue by drzraf** [niccokunzmann/open-web-calendar#104]
Since ICS file format does not support commenting (like prefixing some ICS with `#`), two workaround exists:
- Putting data after `END:VCALENDAR`
- Prefixing lines by `X-`, eg:
```
X-BEGIN:VEVENT
X-UID:3
X-SUMMARY:FOO
X-DTSTART:20220517
X-DTEND:20220801
X-COLOR:yellow
X-END:VEVENT
```

Sadly none of these workarounds work with OWC which fail to parse such a file and does not display any event at all.

**Comment by niccokunzmann** [comment]
If a newline was to be in a calendar Attribute, I think, it would be followed by two newlines.
Can you try this? It might be RFC 5545 compatible
```
X-COMMENT:line1
  Line two
```

**Comment by niccokunzmann** [comment]
The place to make this work is the icalendar library https://github.com/collective/icalendar I will close this here as out of scope but if you like to see this happen or an answer to how to comment, please open an issue there and reference this one. Also, please provide a purpose.
