### ISSUE TITLE
Remove/hide time from Full Calendar

### ISSUE THREAD

**Issue by JMH-Jarbydev** [niccokunzmann/open-web-calendar#107]
Is there a way to remove/hide time from the full calendar? Like Adding something to the Json File to hide Time from the calendar.

**Comment by niccokunzmann** [comment]
Let me know if it works :)

**Comment by niccokunzmann** [comment]
Hi, there probably is... There is a CSS option. If you have a look at the colors: They are CSS. You can use CSS to set an element to "display: none" and it will disappear.
If you use firefox for example, you can right-click on the element, press Q to examine it and click right on the element in the HTML view and copy CSS selector. With that you should be able to modify all of the elements to your liking.

**Comment by niccokunzmann** [comment]
If I add `&css=.event b { display: none; }` to the URL, it hides the times of when the events take place. Is it this what you mean?

Compare:
http://localhost:5000/calendar.html?url=http%3A%2F%2Flocalhost%3A8000%2Fissue_152_broken_characters.ics&date=2023-02-27&css=.event%20b%20{%20display:%20none;%20}
http://localhost:5000/calendar.html?url=http%3A%2F%2Flocalhost%3A8000%2Fissue_152_broken_characters.ics&date=2023-02-27

**Comment by niccokunzmann** [comment]
I close this now as I did not receive an answer and the question is not 100% clear to me. Feel free to leave a comment or open it again if you like to continue the conversation here :)
