### ISSUE TITLE
Docker container improvement ideas

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/open-web-calendar#110]
In #109, @TheMrPhantom added a `Dockerfile` to use the app inside a docker container. Thanks!

More documentation can include
- [x] how to build the docker container
- [x] how to use the app with docker
    - [ ] mapping directories (caching)?
    - [x] how to start
    - [x] how to configure using environment variables

Further, this can be done to make it more usable:
- [x] establish an automatic docker build so one can just pull the container #112
- [x] add a badge for the build, linking to the build
- [x] document how to pull it

**Comment by TheMrPhantom** [comment]
Addressed the following points in #111:
* How to build docker container
* Establish an automatic docker build so one can just pull the container
* document how to pull it

**Comment by TheMrPhantom** [comment]
Todos for @niccokunzmann:
- [ ]  Create github repository secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` with your dockerhub username and push token
- [ ] Create dockerhub repository called `open-web-calendar` to push to
- [ ] Replace `<owner-name>` in `buildAndPush.yml` with dockerhub account name

Todos for @TheMrPhantom:
Add `docker-compose.yml` to repo and readme

**Comment by niccokunzmann** [comment]
Oh no! Closed-source repeats: They made publishing automated builds on dockerhub a pay feature. But, I think Github has something to build containers...

**Comment by niccokunzmann** [comment]
This seems to be a way forward: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by niccokunzmann** [comment]
@TheMrPhantom Sorry, I saw your code too late... I added the workflow which pushes the  image to the dockerhub registry. https://hub.docker.com/r/niccokunzmann/open-web-calendar/

**Comment by niccokunzmann** [comment]
The docker documentation was improved by @TheMrPhantom . There is still missing how to pull the container. It is published as `niccokunzmann/open-web-calendar`.

**Comment by niccokunzmann** [comment]
I completed the documentation for docker from my point of view. If you notice something that can be improved, please write a pull request or a new issue :) Thanks for the cooperation on this one! This is now the main way to deploy new releases.
