### ISSUE TITLE
Color per calendar

### ISSUE THREAD

**Issue by DVDdisk7** [niccokunzmann/open-web-calendar#123]
Hi!
First of all, thx for making this thing, it has saved me a lot of time ;)
I would like to give each source a different color. Is there a way I could do that?

Thanks

**Comment by niccokunzmann** [comment]
Hi, thanks for opening this issue!

I will reference some work on this issue:
- #105 - PR
- #88 - PR
- #52 - issue

It would occur to me that what you are looking for is asked about in #52. Is it? If that is so, please comment there and close this issue - if it is not, I see these ways:

- create a description of how you would like to be able to change the color
- try out what is already provided AND please come back and describe the way you went to make it work.

What do you think of that?
