### ISSUE TITLE
Heroku Free Hosting ends - no reliable hosting location

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/open-web-calendar#125]
At the moment, we use the Heroku free plan for hosting this project. There is no reliable long-term hosting location for this project. This makes it extremely bad for people who have a hard time maintaining their website as this can mean a change in the URL to use.

Ways forward:

1. 10$ recurring monthly contributions to the collective https://opencollective.com/open-web-calendar to continue the current strategy
2. no hosting of open-web-calendar
3. self-hosting of the web app with breaking change in the URL for many users

Which ideas do you have? Which options do you see?

Related: https://github.com/heroku/roadmap/issues/48

**Comment by das-g** [comment]
> Which ideas do you have?

How about
> 3. self-hosting of the web app with breaking change in the URL for many users

but with a transition strategy? Maybe something like this:

1. set up self-hosting and provide it under a domain you control
2. continue to provide https://open-web-calendar.herokuapp.com/ for a limited time, but have it (additionally to displaying the calendar, maybe in a dismissable overlay):
   - indicate when that time will end
   - link to instructions on how to switch to the new URL
3. discontinue to provide https://open-web-calendar.herokuapp.com/ at the indicated time

This is a tad more work, but has all the long-term benefits of option 3 while helping users with the transition.

**Comment by niccokunzmann** [comment]
I am working on creating a hosting solution for all my free apps. This app however needs some help from someone so that users are informed that they should switch... I wonder though where I can host it. If someone can create a PR for that and I just need to change the link, that would be great!

**Comment by studentism** [comment]
Have you considered Render as an alternative? Not sure how long they'll be offering services for free, but it's a pretty seamless transition. I'll throw some $ your way because I've been using your solution recently, but I would maybe suggest focusing more on private deployment at this point. Free solutions will always turn into subscriptions, given enough time and success.

**Comment by niccokunzmann** [comment]
Hi, thanks. I have something running at the moment that would allow me to do the hosting for a bit. If you have a more reliable version than a raspberry pi, feel free to host, too, and we can link it in the Readme.

**Comment by niccokunzmann** [comment]
I did not have time to implement a smooth transition. The service is now hosted in Wales/UK, in the makerspace.
This is the new domain: https://open-web-calendar.hosted.quelltext.eu/
On this little board: https://ammanvalley.foss.wales/t/how-this-forum-is-hosted/13
