### ISSUE TITLE
Add option to provide configuration yaml url

### ISSUE THREAD

**Issue by thoka** [niccokunzmann/open-web-calendar#13]
Consider to provide configuration of the calendar by an URL, pointing to some publicly available yaml or json file. 

Benefits: 
- nice support for big calendars
- add features like templates / color coding of events 
- config file could be group editable beeing served from a github repository

**Comment by niccokunzmann** [comment]
Yes, this is there. It needs to be documented. It is a JSON file. the URL parameter is `specification`.

**Comment by niccokunzmann** [comment]
@thoka #6 is closed now. Would you vote for YML? If not, you can have a look, create new issues and close this one if appropriate.

**Comment by thoka** [comment]
Hm. The main benefit of yaml are comments inside code and better readability.

Are there any drawbacks ?

**Comment by niccokunzmann** [comment]
> Are there any drawbacks ?

Hm. No.

We can use yml with `safe_load`. Would you agree to the following?

---

We can close the issue if 
- [ ] it is possible to load the calendar specification as yml, too
- [ ] it is documented that we can load the specification as yml 
- [ ] we can choose the yml format for specification on the index page or there is an issue for this
- [ ] should there be an example yml file which includes comments and can be used as documentation?
---

**Comment by niccokunzmann** [comment]
@thoka I pushed some functionality. Do you think this issue can be closed? What do you think should be done to close this issue?

**Comment by niccokunzmann** [comment]
I do not want to further this. We can re-open or make new issues for yaml.
