### ISSUE TITLE
Only display current week or upcomming days 

### ISSUE THREAD

**Issue by Stfnrs** [niccokunzmann/open-web-calendar#138]
Hey,

Searched all over the place for somerhing like this, so good! And perfect that I can configure it. 

However one thing would really make my day....I only want to share events for the comming 7 days in a weekschedule or if that not possible only show the current week without giving the viewer the option to toogle back and forth. 

Is there a parameter or something I can do to achive that? Maybe hide the <today> in the corner?

Thanks! 
/S
(I dont know much about coding)

**Comment by niccokunzmann** [comment]
There are already ways to hide buttons. I guess, what you are looking for is to hide the other buttons.

**Comment by Stfnrs** [comment]
Thanks for reply! When configure the calendar on your site i can take away all the buttons except the one in the upper right corner  marked < today > where you can toogle between weeks. Is there a way to leave that option out? The user should not be able to se whats comming up. I will ofcourse contribute if i'll use it or if this involves development.

**Comment by niccokunzmann** [comment]
It depends: adding custom CSS is probably an easy option but if you like to share your solution, adding a button that inserts the CSS is likely appreciated by others, too!

**Comment by niccokunzmann** [comment]
Can you add a screen shot of what you like to have removed because that makes much clearer? Do you like the top bar gone totally for example?

**Comment by Stfnrs** [comment]
![Screenshot_20221201-184516_Samsung Internet](https://user-images.githubusercontent.com/119456339/205128753-db607209-69e9-4a22-b9fb-d3108425374f.jpg)

If it is possible I am looking for this:
1. Take away the bottons that are marked red, prio= must have. 
2. Days are changes so it show the current day to the far left and then following days. This will make the days move ibe step left every day.  Prio =Nice to have.

**Comment by niccokunzmann** [comment]
I tried this and they can be taken away:

https://open-web-calendar.hosted.quelltext.eu/calendar.html?url=https%3A%2F%2Fwww.calendarlabs.com%2Fical-calendar%2Fics%2F46%2FGermany_Holidays.ics&tabs=&controls=date

```
&tabs=&controls=date
```
![image](https://user-images.githubusercontent.com/564768/214066269-60a0ce5c-2444-40bf-b31b-fc95a70d72c4.png)

**Comment by niccokunzmann** [comment]
It can be configured under https://open-web-calendar.hosted.quelltext.eu/
You need to remove the options:
![image](https://user-images.githubusercontent.com/564768/214690481-6363a307-2a7d-4f7e-9c5e-d5e243a39003.png)

I am closing this as completed. Please comment if it is not!
