### ISSUE TITLE
Public website is down

### ISSUE THREAD

**Issue by siurna** [niccokunzmann/open-web-calendar#139]
Seems like [https://open-web-calendar.herokuapp.com/](https://open-web-calendar.herokuapp.com/) is down. Is there anything that could be done about it?

Thanks!

**Comment by niccokunzmann** [comment]
I copied it to https://open-web-calendar.hosted.quelltext.eu/

#125 was open when we could act on that one.

I am happy to receive donations, now that I host it in Wales myself.

**Comment by caco3** [comment]
Thanks for your great tool and thanks for providing a hosted version!

https://opencollective.com/open-web-calendar still points to the non-functional heruko page.

**Comment by stevechief88** [comment]
The new one (https://open-web-calendar.hosted.quelltext.eu/) is now down as well :-(

**Comment by niccokunzmann** [comment]
It should be up again.

**Comment by niccokunzmann** [comment]
@caco3 Thanks, I corrected that. Since I am hosting it, it will be down from time to time for maintenance.

**Comment by niccokunzmann** [comment]
I am closing this as everyone should be aware and the new website is listed in search engines.
