### ISSUE TITLE
Adding a color to a Calendar

### ISSUE THREAD

**Issue by MasterTH-PyPy** [niccokunzmann/open-web-calendar#141]
what do you think about the possibillity to change the color for a multiple calendar overview?

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/141">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/141/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/141/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
My first thought is that there are lots of colors and I wonder which color to change. There are other issues about other colors but I do not know which colors you like to change.

**Comment by MasterTH-PyPy** [comment]
the color of the calender in a multi-calendar view. like in the outlook client. 
then you have a better overview which calendar has an entry an which one not.

we have website with 8 calendars in one view, to have a better overview it is necessary that each calendar has a different color.

**Comment by niccokunzmann** [comment]
Uh, this is clear to me, now. Thank you!

**Comment by niccokunzmann** [comment]
Can you provide an example ICS file? This way, we can make sure it works with that one.

**Comment by MasterTH-PyPy** [comment]
hi,

 

we use multiple ics files

 

 

 
 

Gesendet: Samstag, 28. Januar 2023 um 17:51 Uhr
Von: "Nicco Kunzmann" ***@***.***>
An: "niccokunzmann/open-web-calendar" ***@***.***>
Cc: "MasterTH-PyPy" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [niccokunzmann/open-web-calendar] Adding a color to a Calendar (Issue #141)


 

Can you provide an example ICS file? This way, we can make sure it works with that one.

**Comment by JessJJVW** [comment]
Can we implement this please?

**Comment by niccokunzmann** [comment]
@JessJJVW That is very much possible. You are welcome to give it a go and I can help you figure out how. Do you have any questions?

**Comment by lefebe** [comment]
Has there been an update to this? I would be curious to know if it is possible to do this as well!  Thanks!

**Comment by JessJJVW** [comment]
@niccokunzmann  - sorry, I don't have the skills to do this, I'm simply more of just a user. Could you please implement? Thank you!

**Comment by cruunnerr** [comment]
@niccokunzmann 
If you could just give the event-<div> an id per calendar, then we could use the normal way in the .yml to set up different colors.

for example:

```
.dhx_cal_event.calendar1,
.dhx_cal_event_line.calendar1,
.dhx_cal_event_clear.calendar1,
.dhx_cal_tab.active.calendar1,
.dhx_cal_tab.active.calendar1:hover {
  color: black;
  background-color: orange;
}

.dhx_cal_event.calendar2,
.dhx_cal_event_line.calendar2,
.dhx_cal_event_clear.calendar2,
.dhx_cal_tab.active.calendar2,
.dhx_cal_tab.active.calendar2:hover {
  color: white;
  background-color: blue;
}
```

But therefore we need an ID per calendar. So could you implement an DIV-ID per calendar? Actual there is just an event-id and data-event-id...

**Comment by niccokunzmann** [comment]
>  DIV-ID per calendar

That sounds like a good solution to me! Giving each event a `class` tag that is dependent on the calendar file.

https://github.com/niccokunzmann/open-web-calendar/blob/a90e5f70d6d1e797876a714d102c4a18f95286f2/convert_to_dhtmlx.py#L71

In these lines, the event JSON is generated. The `type` event for example is copied into the `class` attribute.
