### ISSUE TITLE
Fails with Calendar with Lots of Recurring Events

### ISSUE THREAD

**Issue by yasurok** [niccokunzmann/open-web-calendar#170]
It fails with [this ICS file](https://calendar.google.com/calendar/ical/d074ba33f934621a34bc3d5ce10162dbd05964c39c62bc7b5c1b43705c975ef9%40group.calendar.google.com/public/basic.ics). As you can see, it has _tons_ of recurring events. Perhaps that is why the service fails?

When it had only a few such events, the service worked beautifully.

**Comment by niccokunzmann** [comment]
Thanks for reporting this!
[too-many-events-braking-the-calendar.ics.txt](https://github.com/niccokunzmann/open-web-calendar/files/10966659/too-many-events-braking-the-calendar.ics.txt)
I can confirm that it is breaking!
https://open-web-calendar.hosted.quelltext.eu/calendar.html?url=https%3A%2F%2Fgithub.com%2Fniccokunzmann%2Fopen-web-calendar%2Ffiles%2F10966659%2Ftoo-many-events-braking-the-calendar.ics.txt

I see a 502 Bad Gateway by OpenResty. I wonder what that means. It could be that the response is to slow...

**Comment by niccokunzmann** [comment]
#177 can make an improvement - it does on my computer -. A fix should be deployed in v1.9

**Comment by niccokunzmann** [comment]
The latest version does not break any more. Thanks for reporting!

**Comment by yasurok** [comment]
My pleasure. Thanks for fixing it! I apologize for my tardy response!
