### ISSUE TITLE
Customization Option: Hide/Show Days of Weeks

### ISSUE THREAD

**Issue by Emalton** [niccokunzmann/open-web-calendar#172]
When using the week/month calendar views, it would be great if we could choose to hide/show the day of the week. For example, we never have events on Saturday or Sunday so it would be cool to hide those columns.

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/172">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/172/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/172/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
The work week is implemented now. Maybe that is enough for this issue. Please comment/open if you find that the work week does not what you want.
