### ISSUE TITLE
Customization Option: Show event description underneath

### ISSUE THREAD

**Issue by Emalton** [niccokunzmann/open-web-calendar#173]
It would be great if there could be a customization option to show the event's description underneath the event's title, instead of requiring the user to hover over.

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/173">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/173/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/173/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Closing this in favour of #298.
