### ISSUE TITLE
Is there a non docker version of this application

### ISSUE THREAD

**Issue by sysadminpower2019** [niccokunzmann/open-web-calendar#183]
Hello, 

is there a way to run this without docker.
also is there support for ICS feeds with username and passwords?

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/183">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/183/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/183/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Yes, you can run it without docker. Have a look further down on the README. Username and password can be added in the URL like ***@***.*** usually, if I remember correctly. They are visible to everyone, though.

**Comment by sysadminpower2019** [comment]
thanks for the answer. Does this calendar also support caldav?

**Comment by slavkoja** [comment]
While i never used it with this project, the ``vdirsyncer`` is capable to sync caldav with single ICS file. Perhaps it will be usable here too...

**Comment by niccokunzmann** [comment]
@sysadminpower2019 Thanks for creating this issue. Since issue #189 is created now, what do you think it needs to close this issue?

**Comment by niccokunzmann** [comment]
I did not get a reply for a year. I close this. Please comment or open another issue if you still think this needs tending to.

**Comment by sysadminpower2019** [comment]
Well i moved on to gancio.org a pretty great and complete open source
project

On Saturday, April 6, 2024, Nicco Kunzmann ***@***.***> wrote:
> Closed #183 as completed.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/meips/ADKq_NYU3oHqw2Zj4e-HPQxg8BqvCdEDVSGR54CpJlolFgIbCoiddtkL7BCEQi0TCnUBAFjILVXCygr4wqTpDH3DADrTijjDjEYS-i8omAXZAHFDs4YHm-yUhrk3oPYsGn0yV4WRklOcK4PsrYdQNIV8HP57-mkfNxPWzPevzS7ZmBR77EOm2OIzF_2S3_hf_oijw3cGp5evurHmns8Kmc7DNM62c8PrkwGweVpQvuMBhNeEZvPje7FyGRjrUmGfD2wGVBV1ZuiOVi3_pA1jljehHA=s0-d-e1-ft#https://github.com/notifications/beacon/AJWXABXBRW3FB3GFO7ECFLTY4AQZJA5CNFSM6AAAAAAWUS7IGKWGG33NNVSW45C7OR4XAZNWJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XKUY3PNVWWK3TUL5UWJTYAAAAAFYQGSQGQ.gif>Message
ID: <niccokunzmann/open-web-calendar/issue/183/issue_event/
***@***.***>

**Comment by niccokunzmann** [comment]
Thanks! Gancio looks like a really nice project :heart:
