### ISSUE TITLE
Calendar not working

### ISSUE THREAD

**Issue by zyloj** [niccokunzmann/open-web-calendar#199]
First of all, thanks for your work. I'm using open web calendar from some months ago, but in the last days open-web-calendar.hosted.quelltext.eu isn't working.

**Comment by niccokunzmann** [comment]
That is true. There is a power outage in the makerspace that I am hosting it at. I will call in tomorrow and see if they fixed it and maybe unplugged the rock64 board in the process.

**Comment by niccokunzmann** [comment]
I think, I will setup a hetzner server.

**Comment by niccokunzmann** [comment]
Ok. I moved it over. Thanks for getting in touch!

**Comment by niccokunzmann** [comment]
https://open-web-calendar.hosted.quelltext.eu/ should be working again. This time I host it on Hetzner, so that nobody can unplug it. https://xkcd.com/908/

**Comment by niccokunzmann** [comment]
If you (the reader) like to donate so I can run it without interruption, this is very much appreciated.
