### ISSUE TITLE
Add view

### ISSUE THREAD

**Issue by DuklasW** [niccokunzmann/open-web-calendar#200]
MORE SEE. The appearance of the calendar as during "monthly" but the user chooses how many weeks to display, whether one or 2, or all as now.
Adding the option that event descriptions appear under the hour, on the monthly look.
A description of how the css is built, so that you can more easily change the calendar under yourself

**Comment by niccokunzmann** [comment]
Thanks @DuklasW for reporting! I split this up into three issues #201, #202, #203 so that they can be discussed separately and nothing is forgotten. I am closing this then.
