### ISSUE TITLE
12 HR Format

### ISSUE THREAD

**Issue by JessJJVW** [niccokunzmann/open-web-calendar#207]
Can we implement a configuration that allows users to view their events in only the 12 HR Clock instead of the 24 HR format? Thank you!

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/207">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/207/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/207/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
This seems to be possible!

This is a nice issue to start with. Here is a proposed way:
- [ ] Add a choice of common formats to config page
- [ ] Add a field to the default_specification
- [ ] add JavaScript code to load the value into the calendar

Documentation:
- https://docs.dhtmlx.com/scheduler/settings_format.html
- https://docs.dhtmlx.com/scheduler/api__scheduler_hour_date_config.html

Feel free to ask questions if anything is unclear :)

**Comment by niccokunzmann** [comment]
I added this possibility to the index page! Please have a look and let me know that does not solve the issue - or if it does! :)
