### ISSUE TITLE
Let the Calender Viewer, Separate from the Calendar Designer, Choose the Timezone

### ISSUE THREAD

**Issue by yasurok** [niccokunzmann/open-web-calendar#213]
This is related to #170, but is a different matter.

A little background story should help you understand my needs. I run an online English school for Japanese people. I hire teachers from all over the world. During the hiring proces, I need to make sure the applicants can make themselves available for specific time slots this job requires, such as weekeday nights in Japan. This is not a trivial matter because of the time differences.

I created [this ICS file](https://calendar.google.com/calendar/ical/d074ba33f934621a34bc3d5ce10162dbd05964c39c62bc7b5c1b43705c975ef9%40group.calendar.google.com/public/basic.ics) for this purpose. It has a bunch of recurring events with labels that simply state the time in Japan. For example, an 8pm, Wednesday event has the label "8pm, Wed, JST." When the applicants import this ICS file in their favorite calendar app, those events show up _in their local timezone_, so they can easily understand, for example, 8pm, Wednesday, JST, corresponds to what time in their local timezone.

I initially wanted to use Open Web Calendar for this purpose, but I could not because of #170. However, now that it has been resolved, I would like to give it another go. 

Unfortunately, there is another problem. I, as the calendar _designer_, as it were, want to specify what ICS file to show. [This is a sample result](https://open-web-calendar.hosted.quelltext.eu/calendar.html?url=https%3A%2F%2Fcalendar.google.com%2Fcalendar%2Fical%2Fd074ba33f934621a34bc3d5ce10162dbd05964c39c62bc7b5c1b43705c975ef9%2540group.calendar.google.com%2Fpublic%2Fbasic.ics). However, I want the calender _viewer_, to be able to set his local timezone. I have no knowledge of the applicants timezones so I cannot set one for the calendar. They are the ones who need to see this ICS file in their timezone, not I. 

I would think Open Web Calendar assumes the calendar designer and the calendar viewer are the same. My use case is a scenario where the calendar designer and the calendar viewer are not the same person. So this may not the kind of needs Open Web Calendar is meant to serve, but if you could implement this feature, I would appreciate it very much.

Thanks!

Yasuro

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/213">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/213/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/213/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Hi, I think, at the moment, the time zone of the calendar moves automatically to the time zone of the viewer. Can you check? Here is my view attached.

Do you want people to choose additionally?

**Comment by niccokunzmann** [comment]
I am wondering about an option: When yo click on the ?, you could see a text: "You are viewing the calendar in this time zone: ... You can choose to view the calendar in these time zones:" dropdown menu.

**Comment by yasurok** [comment]
Hi, @niccokunzmann! Thanks a lot for your prompt response!

> Hi, I think, at the moment, the time zone of the calendar moves automatically to the time zone of the viewer. Can you check? Here is my view attached.

That's great info! I had no idea. I cannot really check myself with the ICS file I created (because that's created with the JST in mind and I am viewing the calendar with JST as the default timezone), but your screenshot seems to indicate that you are right.

That's good enough in most cases, but... (continued below)

> Do you want people to choose additionally?

... I actually do. I know I am asking for a lot, but some applicants for my job are what are called "digital nomads." They are those who periodically migrate from one country to another, staying at one place only for a short period of time. Such people would want to see my calendar in all the timezones that they could possibly be in.

> I am wondering about an option: When yo click on the ?, you could see a text: "You are viewing the calendar in this time zone: ... You can choose to view the calendar in these time zones:" dropdown menu.

Are you saying you are thinking of offering this feature? If you are, yes, that would be awesome!

I did not understand your intention at first, so I clicked on the "?" on the lower right corner and got the following screen, and wondered, "Where is that text? Where is that dropdown menu?" Silly me. 😁

![Sample of what I get when I click on "?"](https://i.imgur.com/y4WF7n5.png "Sample of what I get when I click on \"?\"")

**Comment by niccokunzmann** [comment]
When you click on the `?`, something like this could be added:

![image](https://github.com/niccokunzmann/open-web-calendar/assets/564768/c1851ab5-5fb8-4a34-a086-9275e60ccd06)

**Comment by yasurok** [comment]
@niccokunzmann Looks great to me!

**Comment by niccokunzmann** [comment]
Ah. Ok, good to know! Then I know what it takes to implement this.

I would like to invite you to translate the calendar if you find that it is not how you like it in Japanese: https://hosted.weblate.org/projects/open-web-calendar/

I am doing this in the free time and I did #170 because it was technically possible now but not when I created project. I will consider this in my free time. If you want me to implement this with a higher priority, you could contribute to me or the project :)

Apart from this: It is already possible to view the calendar in another time zone. [timezone=Asia%2FHong_Kong](https://open-web-calendar.hosted.quelltext.eu/calendar.html?url=https%3A%2F%2Fwww.calendarlabs.com%2Fical-calendar%2Fics%2F46%2FGermany_Holidays.ics&timezone=Asia%2FHong_Kong) can be added to the end of the URL. I did not find what the name for JST is. So, if you choose a time zone from the list at https://open-web-calendar.hosted.quelltext.eu/, you can see that it gets added to the URL and then, you can add this to your calendar URL, too to view it in a different time zone.

What do you think about these different ideas?

**Comment by yasurok** [comment]
> if you translate the project to Japanese, I implement this feature.

That is a fair proposition, and I would consider it. However, right now I cannot commit to it due to time constraints. So I will understand if you do not want to implement this feature until I do.

> It is already possible to view the calendar in another time zone. [timezone=Asia%2FHong_Kong](https://open-web-calendar.hosted.quelltext.eu/calendar.html?url=https%3A%2F%2Fwww.calendarlabs.com%2Fical-calendar%2Fics%2F46%2FGermany_Holidays.ics&timezone=Asia%2FHong_Kong) can be added to the end of the URL.
> What do you think about these different ideas?

Actually I knew this feature was there. The problem is that I cannot expect the job applicant to be able to manipulate the URL by himself properly; they are not tech experts. Alternatively, I could create and provide a list of URLs each of which corresponds to a timezone, and have him choose his. I could certainly do this, but the list is going to be ginormous.

Come to think of it, even if I let him choose his timezone from a pulldown menu, he'll have to go through a ginormous list of the same length anyway. So maybe it is not such a bad idea.

**Comment by niccokunzmann** [comment]
@yasurok, I created #221. Once merged, it will come online after a while. Could you check if the issue can be closed?

**Comment by yasurok** [comment]
@niccokunzmann Thanks. That's fantastic news! I am very willing to test it out, but so far it has not come online yet. I will check back again later!

**Comment by niccokunzmann** [comment]
If you would like to change the formulation, that is welcome, too. My problem was finding a short one that does not sound too technical.

**Comment by yasurok** [comment]
@niccokunzmann Thank you very much. 

By the way, I gave it a shot just now but the new feature still does not seem to be in the "production" version.

**Comment by niccokunzmann** [comment]
oh. the automatic update is running now

**Comment by yasurok** [comment]
@niccokunzmann The new feature confirmed! Looks super slick! Thanks a lot! 😁

**Comment by niccokunzmann** [comment]
Cool! Feel free to contribute whenever you have time, no pressure - it is a free project, you are invited.
