### ISSUE TITLE
Valid ICS gives a ValueError

### ISSUE THREAD

**Issue by siurna** [niccokunzmann/open-web-calendar#225]
Hey,
I can't seem to get ICS display working.

My current working environment:
- ICS file: dynamically generated feed: https://paslaugos.btt.lt/endpoints/btt/v1/calendar/f02016f28eee9f632b76c68310f71d1b-1
- ..which seems to be perfectly valid: https://icalendar.org/validator.html?url=https://paslaugos.btt.lt/endpoints/btt/v1/calendar/f02016f28eee9f632b76c68310f71d1b-1. Apple Calendar, other apps and web validators seems to parse the file just fine.
- I have branched a fresh, unmodified version for testing: https://web-ics-9-11-23.vercel.app/

Yet I am getting an error attached. I have used open-web-calendar before and it seemed to work without much issues. Could you please give me hint what am I doing wrong?

Appreciate the help

<img width="982" alt="Screenshot 2023-09-11 at 11 39 25" src="https://github.com/niccokunzmann/open-web-calendar/assets/988062/192bea45-fe6f-4605-bfe0-d7c898f7208e">

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/225">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/225/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/225/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Thanks! This looks like this could be reported to collective/icalendar.
I can do that once I checked the file.

**Comment by niccokunzmann** [comment]
Hm. It seems that the content that the open-web-calendar receives is empty. I wonder why that is.

**Comment by niccokunzmann** [comment]
Oh. requests is forbidden to access this URL:

```
>>> import requests
>>> requests.get("https://paslaugos.btt.lt/endpoints/btt/v1/calendar/f02016f28eee9f632b76c68310f71d1b-1").content
b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don\'t have permission to access this resource.</p>\n</body></html>\n'
```

**Comment by niccokunzmann** [comment]
It seems to require a header.

```
requests.get("https://paslaugos.btt.lt/endpoints/btt/v1/calendar/f02016f28eee9f632b76c68310f71d1b-1", headers={"user-agent": "open-web-calendar"}).content
```

**Comment by niccokunzmann** [comment]
I pushed the fix. It should be deployed soon.
