### ISSUE TITLE
Incorrect mime-type for configuration.js

### ISSUE THREAD

**Issue by nebulade** [niccokunzmann/open-web-calendar#241]
Hi, first of all thanks for the great app! I am currently packaging it for [Cloudron](https://cloudron.io) and came across an issue, where our reverse proxy in front of the app sets `X-Content-Type-Options: nosniff` which results in the browser refusing to use for example .js files which have the wrong `content-type` header. The first such issue I came across was the [configuration.js](https://github.com/niccokunzmann/open-web-calendar/blob/93e4863df6dc7e964fb77791bb169ff015c4fb74/app.py#L202) route which is delivered as `text/html`.

For example firefox will report as:
```
The resource from “https://cal.domain.com/configuration.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

I am not a python developer or know flask much, but is there a way to set the content type correctly or am I totally on the wrong path here?

Potentially other routes also have the wrong mime-type, will get to that later if any.

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/241">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/241/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/241/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Thanks for spotting this! Yes, the content type should be relatively easy to set... I will have a look.

**Comment by niccokunzmann** [comment]
I created [this](https://github.com/pallets/flask/issues/5361) to correctly set the mime type in flask automatically. However some are not set on OWC side - not flasks fault.

**Comment by niccokunzmann** [comment]
Hi @nebulade, I set the content type in #243. Please check if that works for you! If it does, you can close the issue.

**Comment by nebulade** [comment]
Great, thanks for the fast fix. I've just built an app package from that sha and it works as expected!
