### ISSUE TITLE
Show only working days

### ISSUE THREAD

**Issue by Gomercic** [niccokunzmann/open-web-calendar#258]
Is it possible that only the days from Monday to Friday without Saturday and Sunday are displayed in week view?

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/258">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/258/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/258/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
@Gomercic and @Emalton have a look. The new version should be deployed within 24h and you should be able to configure the week to only display the work week.

When I wonder is the days: At this moment, one can choose to click through the days and end up on the Sunday. That is not desired, right?

**Comment by Emalton** [comment]
Not desired for me. An extra bonus would be if there was a configuration for the relative days before and after the current date to display.

**Comment by niccokunzmann** [comment]
> An extra bonus would be if there was a configuration for the relative days before and after the current date to display.


I think, it is worth opening an additional issue to work on this one.

- [ ] I would set the closing criteria for this one to skip the days Su/Sa with the next/last buttons.

**Comment by niccokunzmann** [comment]
This is fixed by #293.
