### ISSUE TITLE
provide ical output

### ISSUE THREAD

**Issue by thoka** [niccokunzmann/open-web-calendar#27]
I would like to use this software to aggregate different calendars into one. 
If it would support rendering to ical, I could use it as input source to other ical based services.

**Comment by niccokunzmann** [comment]
For only aggregating calendars into one ICAL feed, you can see the [calender_merger](http://calender-merger.herokuapp.com/). Would that fit your use case?

**Comment by thoka** [comment]
Hm. There is overlap of interest in calendar_merger and this one. 
Yes, one could add functionality from here to calendar_merger to.
I would recommend to join these two projects into one.

**Comment by niccokunzmann** [comment]
You can do that. http://www.instantcal.com/api.html which I aim to replace allows these

    iCal - an iCalendar file
    Webcal - a webcal calendar
    RSS - an RSS feed
    Twitter - a Twitter feed

Providing conversion from different sources to ICal and a calandar does not make so much sense to me, so I will not work on this.

**Comment by niccokunzmann** [comment]
#35 We can generate an ICAL output. If you like, you can document this in the API.md file. I would like to work more documentation first, since the project has transitioned from the Minimal Working Prototype now to something usable and extend-able.

**Comment by niccokunzmann** [comment]
Hm. I also think that this is not too much work. It would probably be easy to convert the events to ICal, too.
Also, once we have a calendar which has several sources, subscribing with ical is more user friendly than subscribing to each source. Ical output would keep the single configuration point intact.
