### ISSUE TITLE
Export as image

### ISSUE THREAD

**Issue by flaschenge1st** [niccokunzmann/open-web-calendar#303]
Hi there!

Is it possible to "export" the result as an image? Maybe as a feature request?
Right now, it's only possible to render the calendar and screenshot the view.

Thank you for any hints!

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/303">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/303/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/303/pledge.svg">
</picture>
</a>

**Comment by vmario89** [comment]
i guess this will not be a part of the core functionality. Even programs like Grafana do not render their stuff by own. They use some external lib. Maybe use https://phantomjs.org/api/webpage/method/render.html

to render by command, you can use chrome/chromium for example:

`"%ProgramFiles%\Google\Chrome\Application\chrome.exe" --incognito --headless=old --disable-gpu --screenshot=%cd%\calendar.png --window-size=600,800 --virtual-time-budget=15000 --timeout=5000  "https://owc.somewhere.org/calendar.html?url=YOURLURL"
`

you may need to mess up with the headless and gpu switches to make it work. it depends ;-)

**Comment by flaschenge1st** [comment]
OK, thank you!
I already feared something like this: I guess most of the (cheap) web site packages do not feature a headless chrome install. 
But that's not OWCs problem, I see! :-) 

I close this as "won't fix" - if anyone wants to re-open and fix it: Yay, thank you!
