### ISSUE TITLE
provide a complex example

### ISSUE THREAD

**Issue by thoka** [niccokunzmann/open-web-calendar#34]
I would like to have a calendar showing different public icals  with different colors.

Please provide an example configuration file realizing this.

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/34">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/34/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/34/pledge.svg">
</picture>
</a>

**Comment by thoka** [comment]
There is an example at: https://raw.githubusercontent.com/Chaostreff-Potsdam/Chaostreff-Potsdam.github.io/master/calendar-specification.json

It is one source only and no configuration of colors.

**Comment by thoka** [comment]
Currently I try with https://gist.github.com/thoka/2fa434da5cafa559061e665465be870f

json url: https://gist.githubusercontent.com/thoka/2fa434da5cafa559061e665465be870f/raw/calendar.json

But
https://open-web-calendar.herokuapp.com/calendar.events.json?specification=https%3A%2F%2Fgist.githubusercontent.com%2Fthoka%2F2fa434da5cafa559061e665465be870f%2Fraw%2Fcalendar.json
returns only international holiday events.

**Comment by niccokunzmann** [comment]
Would be https://open-web-calendar.herokuapp.com/calendar.spec?specification_url=https%3A%2F%2Fgist.githubusercontent.com%2Fthoka%2F2fa434da5cafa559061e665465be870f%2Fraw%2Fcalendar.json The parameter is `specification_url`

**Comment by niccokunzmann** [comment]
![image](https://github.com/niccokunzmann/open-web-calendar/assets/564768/3fac69bf-273a-4ef5-9317-090de92b097b)
