### ISSUE TITLE
Change event colors to match Google Calendar colors

### ISSUE THREAD

**Issue by Creasiion** [niccokunzmann/open-web-calendar#376]
I was just wondering if there was a customizable feature to display our event colors. All of my events are under the same Gcalendar, but I changed their event color to organize them (i.e. red for due dates, blue for work).
Here is an example of what I mean, They're not different calendars, just different event colors, other than mother's day ofc.
![image](https://github.com/niccokunzmann/open-web-calendar/assets/129997790/85716079-f1b2-479e-8d33-75e943d5d1b9)

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/376">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/376/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/376/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Hi, could you attach the ICS file, too?

**Comment by Creasiion** [comment]
> Hi, could you attach the ICS file, too?

It won't let me attach the .ics file, can I email it to you?

**Comment by niccokunzmann** [comment]
Ah yes, you can email me. I have to rename them to .txt at the end.

**Comment by Creasiion** [comment]
Alright I sent you the email with the .ics

**Comment by niccokunzmann** [comment]
@Creasiion I am sorry but I did not receive an email. Could you copy the file content into a comment or attach it with .txt at the end?

**Comment by niccokunzmann** [comment]
When I look at the export, the events do not contain colors. Google does not share this freely.

```
BEGIN:VEVENT
DTSTART:20240522T140000Z
DTEND:20240522T170000Z
DTSTAMP:20240524T193024Z
UID:45t795esgjgteuul238laemjhf@google.com
CREATED:20240524T192725Z
LAST-MODIFIED:20240524T192725Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:TEST COLOR3
TRANSP:OPAQUE
END:VEVENT
```

The course of action here is to petition Google to export this. While you might face structural ignorance, it is still worth doing.

If you like to create a similar result, you could use categories/tags. They can be colored. A hoster with less market power might also treat matters of cooperation/interoperability as more important and within their business model. I would like to express my sadness, too. Seeing it plausable that your freedom of expression might become victim of a power imbalance here. And wish you well in this struggle to liberate your data from a company who might treat it as theirs. Let me know if I can be of any help.

**Comment by niccokunzmann** [comment]
The only thing I can offer here for now is using  tags: https://open-web-calendar.quelltext.eu/templates/

**Comment by niccokunzmann** [comment]
I am sorry that I cannot help with this for now as Google does not reveal which colours it uses. I will close this for now but feel free to continue to comment or open it again.
