### ISSUE TITLE
links not shown in description

### ISSUE THREAD

**Issue by kamazeuci** [niccokunzmann/open-web-calendar#388]
I am importing this ICS
https://gancio.antroposofiachile.net/feed/ics

From this calendar
https://gancio.antroposofiachile.net/

But On open web calendar
https://owc.antroposofiachile.net/calendar.html?url=https%3A%2F%2Fgancio.antroposofiachile.net%2Ffeed%2Fics

 it won't show the links to the events.
Although, on other calendar clients, it does show them.

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/388">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/388/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/388/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
I upload the file for future reference:
[gancio.antroposofiachile.net.ics.txt](https://github.com/user-attachments/files/15523113/gancio.antroposofiachile.net.ics.txt)

I can see this field:

```
URL:https://gancio.antroposofiachile.net/event/el-significado-espiritual-de
	-las-envolturas-embrionarias-a-la-luz-de-la-antroposofia
```

I think, this is not processed at the moment. Could you tell me how you would like this to show up?
I.e. the title could be the link or there could be something like this [Onebox from Discourse](https://meta.discourse.org/t/create-rich-link-previews-with-onebox/98088) or an extra link...

**Comment by kamazeuci** [comment]
@niccokunzmann thanks for your great attitude towards this. I think that the link in the title would be the most intuitive, simple, minimal, straight forward way to render it. That's my humble opinion.

thanks!!

**Comment by niccokunzmann** [comment]
@kamazeuci, thanks for reporting this. It took me a bit of time and the feature is there, see #397. It should be life in the next 48 hours.

**Comment by niccokunzmann** [comment]
@kamazeuci I would like to collect instances and also show links to existing calendars and how they are used. Could I add yours to the pages in the documentation that I would like to create for this? https://antroposofiachile.net/home/

**Comment by kamazeuci** [comment]
thanks @niccokunzmann !! and yes, of course, you can use our website as an example.. very glad to humbly contribute in some way to your work. thanks for it!

**Comment by niccokunzmann** [comment]
@kamazeuci, I just noticed that Firefox cannot load the website:
![image](https://github.com/user-attachments/assets/79c43c77-50a7-4f25-b150-6f19cfec4490)
