### ISSUE TITLE
Specify start of week

### ISSUE THREAD

**Issue by davisdude** [niccokunzmann/open-web-calendar#39]
Would it be possible to add an option to specify which day of the week to use as the start?

For instance, maybe something like:

```
src="...&amp;skin=...&amp;startdow=sun" 
```

**Comment by niccokunzmann** [comment]
Yes, it is possible. How much are you willing to invest?
Documentation: https://docs.dhtmlx.com/scheduler/configuration.html#schedulerconfig

**Comment by niccokunzmann** [comment]
Would you need Monday or Sunday or should this be any day possible?

**Comment by davisdude** [comment]
I think only Sunday and Monday would be needed.

**Comment by niccokunzmann** [comment]
@davisdude I will not do it until I see use for me. However, I am willing to help you get what you need.

To have this functionality for you and your server, fork it, add the one line from the documentation to make it Sunday, and click the Heroku button. It is one line of programming.

If you like it and you like to share it with others, It should be about 2 lines of JavaScript, 2 lines of text and 8 lines of HTML.

**Comment by garbled1** [comment]
I'm trying to understand this answer.  What file do I add that line to?  I'm not running it in heroku, I'm running locally via a gunicorn, so do I just need to edit one of the static js files?

**Comment by TylerB260** [comment]
@garbled1 Late response, but I just made this change myself. It's in the open-web-calendar/static/js/configure.js file.

It's in the loadCalendar function, I edited mine to read this way:
![image](https://user-images.githubusercontent.com/5327096/135485114-396dfdbf-35a9-429f-b4a6-85b2a2713cc4.png)

Just be sure to clear your cache after making the change.

**Comment by IBC-IT** [comment]
Trying to get this working using https://open-web-calendar.herokuapp.com
Is this not possible using the web interface?

**Comment by niccokunzmann** [comment]
That looks like something that would be quote easy to implement. If someone likes to do it.
1. Add a choice to the web interface
2. add the parameter to the URL
3. at the line specified by @TylerB260 [here](https://github.com/niccokunzmann/open-web-calendar/issues/39#issuecomment-931428590), read the parameter and write it into the code. Other parameters have been parsed before so that should be more copy&paste

**Comment by niccokunzmann** [comment]
See also #138 - the idea is to have the day moving as the current day.

**Comment by niccokunzmann** [comment]
Thanks everyone and thanks for a donation. Choosing between Monday and Sunday is included in the version 1.6 as an option to choose from. This should go live on my instance in a few hours.
