### ISSUE TITLE
Allow option: Day to display

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/open-web-calendar#4]
Set a fixed day to display, Format should be YYYY-MM-DD. This should be in the specification/url parameter.

**Comment by jmirabel** [comment]
Thank you for this app. Date specification would be wonderful !

**Comment by niccokunzmann** [comment]
The date specification is not in the configuration page but you can set the `date` parameter. `date=2023-01-23`

See also: https://github.com/niccokunzmann/open-web-calendar/pull/149

**Comment by niccokunzmann** [comment]
I close this as the issue does not specify that this should be configured in the GUI. So, please open an issue if you think this is useful.
