### ISSUE TITLE
Daylight savings/current time is 1 hour off?

### ISSUE THREAD

**Issue by joe-claire** [niccokunzmann/open-web-calendar#460]
Not sure how to fix this but I set the time to my browser time and it's an hour behind.

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/460">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/460/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/460/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Hi, thanks for reporting this!

Could you help me check that so I can fix this with as much as possible of the following?

- Screenshot
- Calendar URL
- Your time zone (I think it shows that when you edit the calendar)
- The date you are viewing

**Comment by joe-claire** [comment]
I actually reloaded the page and it resolved!

**Comment by niccokunzmann** [comment]
Great news! Thanks!
