### ISSUE TITLE
different source colours or prefixes

### ISSUE THREAD

**Issue by fnetX** [niccokunzmann/open-web-calendar#52]
Hey, 

When using multiple calendar sources, it might be a nice idea to specify keep them distinguishable, e.g. by using different (background / highlight) colours or prefixes for each of them. 

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/52">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/52/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/52/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
There seems to be an in official attribute for color: `X-APPLE-CALENDAR-COLOR`
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:chaostreff-potsdam
X-APPLE-CALENDAR-COLOR:#CACBCD
END:VCALENDAR
```

This seems to be used by nextcloud

**Comment by id-ic** [comment]
Pardon my ignorance but how would you add that?

**Comment by niccokunzmann** [comment]
Each event goes through Javascript. That could be the place. Also, the attribute might need to be copied over from the Python event object into the JSON data that is sent to the website by flask.

**Comment by goreavin** [comment]
@niccokunzmann : I have now added the above attribute but still no change in the calendar colors... Am I missing something?

CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:HCY
X-APPLE-CALENDAR-COLOR:#94e3a8
BEGIN:VEVENT
DTSTART:20210901T140000Z
DTEND:20210901T150000Z
CREATED:20211001T083933Z
DTSTAMP:20211001T084933Z
LAST-MODIFIED:20211001T084933Z

**Comment by barnabycollins** [comment]
Going off the [DHTMLX docs](https://docs.dhtmlx.com/scheduler/custom_events_color.html), am I right in thinking that adding the following line or similar to the return statement [/convert_to_dhtmlx.py](convert_to_dhtmlx.py):42:
```python
"color": calendar_event.get("X-APPLE-CALENDAR-COLOR", ""),
```
would at least get the background colour changing for coloured events?

Additionally, the below line might be needed:
```python
"textColor": "#ffffff",
```
assuming that the calendar program has provided colours with high enough contrast from white.

**Comment by niccokunzmann** [comment]
As linked in the Pull Requests above, now you can change the color of the calendars.
