### ISSUE TITLE
Find another place to host the app

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/open-web-calendar#58]
Currently, we are hosting the app on a free dyno on heroku.
This free dyno is used up by 80%, according to an e-mail.
So, if we add another place to host the app,
future users do not use up the free hours.
If anyone has a suggestion, it is welcome. If you would like to click the hosting button, start a new free dyno and add a Github synchronization, this is very welcome!

**Comment by SuperSandro2000** [comment]
Could this be done on GitHub pages somehow?

**Comment by niccokunzmann** [comment]
Hi,

this can not be done on GithubPages as it creates static pages. I tried
this and failed because e.g. NextCloud offers access to the ICS
calendars shared by HTTP but does not allow websites to access them.
Only the server backend can offer this access.
