### ISSUE TITLE
minor translation typo

### ISSUE THREAD

**Issue by ines-rana** [niccokunzmann/open-web-calendar#59]
In file static/js/dhtmlx/locale/locale_el.js the day of the week names array contains "Κυριακή" ("Sunday") twice:

`day_full:["Κυριακή","Δευτέρα","Τρίτη","Τετάρτη","Πέμπτη","Παρασκευή","Κυριακή"]`

It should read

`day_full:["Κυριακή","Δευτέρα","Τρίτη","Τετάρτη","Πέμπτη","Παρασκευή","Σάββατο"]`

**Comment by niccokunzmann** [comment]
Thanks! If you like, you can fix it here. Note that this is copied from
the xhtmlscheduler web page, so they would probably be interested to
change that for other users, too.

**Comment by niccokunzmann** [comment]
https://forum.dhtmlx.com/t/open-web-calendar/69840/3?u=niccokunzmann

Fixed! Thanks for reporting!
