### ISSUE TITLE
Define start hour to display

### ISSUE THREAD

**Issue by Lo0ping** [niccokunzmann/open-web-calendar#68]
Hi, 
thanks for your work :)
I just purpose you an little UI feature.

By default, in week view, calendar is positionned on 00:00 even if I have only late  events. 
So, is it possible to
- Define default hour position on week view 
AND/OR
- Automatically define default hour position (ie : 30mn before) from the earliest event hour in the week  

thanks again

**Comment by niccokunzmann** [comment]
I like this, too.
This is an open-source software and you can add this feature if you like. I will do it if I like.
Just for curiosity: Where do you use it?
Also, did you see that since #67, you can choose the week view as a default tab using `tab=week` as a parameter?

**Comment by niccokunzmann** [comment]
I wonder what you think about this: The week view could be scrolled to start at the current time.

Additionally:
- documentation of the week view: https://docs.dhtmlx.com/scheduler/week_view.html
- configuration such as first hour and last hour: https://docs.dhtmlx.com/scheduler/configuration.html

**Comment by Lo0ping** [comment]
Hi, 
I have discovered it while searching an ics viewer.

I have see the new feature for week view by default, great !!! 👍

**Comment by niccokunzmann** [comment]
I think, this feature is there from version 1.8 now.

![image](https://github.com/niccokunzmann/open-web-calendar/assets/564768/146066a3-706f-47ec-b11d-e50b0773bbc8)

I will close this. Feel free to open it again! Thanks for the conversation!
