### ISSUE TITLE
[Bug] "UID" error

### ISSUE THREAD

**Issue by KaKi87** [niccokunzmann/open-web-calendar#69]
Hello, I created a NodeJS module which generates [an ICS file](https://cestlagreve.api.kaki87.net/ics), which [works properly in Google Calendar](https://media.discordapp.net/attachments/466563785306669086/684745351483490324/Screenshot_20200304-135209_Agenda.png), but I wanted to embed it using a more beautiful tool than Google's which hasn't been updated for years.

However, I'm experiencing a strange error, which only shows the message `UID` :

```js
'UID'

Traceback (most recent call last):
  File "/app/conversion_base.py", line 50, in retrieve_calendar
    self.collect_components_from(calendars)
  File "/app/convert_to_dhtmlx.py", line 100, in collect_components_from
    json_event = self.convert_ical_event(event)
  File "/app/convert_to_dhtmlx.py", line 40, in convert_ical_event
    uid = calendar_event["UID"]
  File "/app/.heroku/python/lib/python3.7/site-packages/icalendar/caselessdict.py", line 42, in __getitem__
    return super(CaselessDict, self).__getitem__(key.upper())
KeyError: 'UID'
```

[Here's the embed](https://openwebcalendar.herokuapp.com/calendar.html?url=https://cestlagreve.api.kaki87.net/ics).

Thanks

**Comment by niccokunzmann** [comment]
That error means that the calendar expects a UID in the event.

> This property is an important method for group scheduling applications to match requests with later replies, modifications or deletion requests. Calendaring and scheduling applications **MUST** generate this property in "VEVENT", "VTODO" and "VJOURNAL" calendar components to assure interoperability with other group scheduling applications. This identifier is created by the calendar system that generates an iCalendar object. - [ICS Specification](https://www.kanzaki.com/docs/ical/uid.html)

Where do you think should a change happen?
It is easy to remove the error in this application. It is this line:
https://github.com/niccokunzmann/open-web-calendar/blob/6246a7a3f291f55a3f028d9685fa42fc754378a1/convert_to_dhtmlx.py#L40

Do you have access to the source code of the ics generator and would like to change it there or is this out of scope so that this software would be the one which needs to be changed?

**Comment by KaKi87** [comment]
I created the generation script myself so yes I can modify whatever it is necessary to.
However, adding a UID field just to have it would be ridiculous since the events are automatically generated at every HTTP request from another source which only provide an event name and a link.

**Comment by niccokunzmann** [comment]
Then, let's do it here. Would you like to do it?

**Comment by niccokunzmann** [comment]
I think, we can just use `uid = calendar_event.get("UID")` instead of `uid = calendar_event["UID"] `.

**Comment by niccokunzmann** [comment]
Okay @KaKi87 It is done and works!

**Comment by KaKi87** [comment]
Very well, thanks !
