### ISSUE TITLE
Times all off by 5 hours & All day events showing in 2 days

### ISSUE THREAD

**Issue by id-ic** [niccokunzmann/open-web-calendar#75]
All my appointments are off by 5 hours.  I'm assuming this is just a TZ issue somewhere but I don't see where to adjust this.

Also, my all day events show on the day before (because 00:0) and the day of. How can I just have it show on the day it's set for?

**Comment by niccokunzmann** [comment]
Can you provide the ics link, one event, the expectation and the actual view as well as a screen shot? This helps reproduce and talk about the same. The Ics file can also be edited to remove personal information.
Thanks for reporting!

**Comment by id-ic** [comment]
Wow .. that was embarrassing. ignore me.  Wrong project.
